run:
	@make build
	java -cp bin Main

build:
	javac -d bin Main.java

clean:
	rm -r bin
	clear

git:
	@git config --global user.name "jailsonneve"
	@git config --global user.email "daiarthur053@gmail.com"
	
testeAula04:
	javac -d bin Teste/TesteAula04.java
	java -ea -cp bin Teste/TesteAula04
